INSERT INTO `Artist` (`name`, `genre`)
VALUES ('AC/DC', 'Heavy Metal'),
    ('Arcade Fire', 'Indie Rock'),
    ('Arctic Monkeys', 'Indie Rock'),
    ('Ben Harper', 'Folk Rock'),
    ('Bill Withers', 'Soul'),
    ('Billy Bragg & Wilco', 'Alternative Rock'),
    ('Black Sabbath', 'Hard Rock'),
    ('Blitzen Trapper', 'Alternative Country'),
    ('Bob Dylan', 'Folk Rock'),
    ('Bob Marley', 'Reggae'),
    ('Bryan Adams', 'Rock'),
    ('Cat Stevens', 'Folk'),
    ('Chvrches', 'Synthpop'),
    ('Coldplay', 'Alternative Rock'),
    ('Conor Oberst', 'Indie Folk'),
    ('Dave Matthews', 'Rock'),
    ('David Bowie', 'Rock'),
    ('DeVotchKa', 'Indie Folk'),
    ('Dispatch', 'Indie Folk'),
    ('Don McLean', 'Folk Rock'),
    ('Donovan', 'Folk'),
    ('Elton John', 'Pop Rock'),
    ('Elvis Perkins', 'Folk'),
    ('Emmylou Harris', 'Country'),
    ('Father John Misty', 'Indie Folk'),
    ('First Aid Kit', 'Folk'),
    ('Florence + The Machine', 'Indie Pop'),
    ('Fun', 'Indie Pop'),
    ('Gin Blossoms', 'Alternative Rock'),
    ('Guns N Roses', 'Hard Rock'),
    ('Harry Chapin', 'Folk Rock'),
    ('Jack Johnson', 'Folk Rock'),
    ('Jason Mraz', 'Pop'),
    ('Jimmy Buffett', 'Country Rock'),
    ('John Lennon', 'Rock'),
    ('John Mellencamp', 'Rock'),
    ('Johnny Cash', 'Country'),
    ('Journey', 'Rock'),
    ('Keane', 'Alternative Rock'),
    ('Led Zeppelin', 'Rock'),
    ('Lynyrd Skynyrd', 'Southern Rock'),
    ('Mason Jennings', 'Folk'),
    ('Metallica', 'Heavy Metal'),
    ('Michael Jackson', 'Pop'),
    ('Miley Cyrus', 'Pop'),
    ('Neil Young', 'Rock'),
    ('Nirvana ', 'Grunge'),
    ('OAR', 'Rock'),
    ('Oasis', 'Britpop'),
    ('Of Monsters and Men', 'Indie Folk'),
    ('Paul Simon', 'Folk Rock'),
    ('Pink Floyd', 'Rock'),
    ('Queen', 'Rock'),
    ('Radiohead', 'Alternative Rock'),
    ('Red Hot Chili Peppers', 'Alternative Rock'),
    ('Refused', 'Hardcore Punk'),
    ('Regina Spektor', 'Indie Pop'),
    ('Ricky Nelson', 'Rock and Roll'),
    ('She & Him', 'Indie Pop'),
    ('Stealers Wheel', 'Rock'),
    ('Sublime', 'Ska Punk'),
    ('Taylor Swift', 'Pop'),
    ('The Avett Brothers', 'Folk Rock'),
    ('The Band', 'Rock'),
    ('The Beatles ', 'Rock'),
    ('The Black Keys', 'Rock'),
    ('The Byrds', 'Rock'),
    ('The Church', 'Alternative Rock'),
    ('The Clash ', 'Punk'),
    ('The Cure ', 'Post-Punk'),
    ('The Doors ', 'Psychedelic Rock'),
    ('The Eagles', 'Rock'),
    ('The Killers', 'Indie Rock'),
    ('The Kinks', 'Rock'),
    ('The Lumineers', 'Indie Folk'),
    ('The Ramones ', 'Punk'),
    ('The Rolling Stones ', 'Rock'),
    ('The Shins', 'Indie Rock'),
    ('The Smiths ', 'post-Punk'),
    ('The Stooges ', 'proto-Punk'),
    ('The Strokes', 'Indie Rock'),
    ('The Tallest Man on Earth', 'Folk'),
    ('The Velvet Underground ', 'Art Rock'),
    ('The White Stripes', 'Alternative Rock'),
    ('The Who ', 'Hard Rock'),
    ('The Zombies', 'Rock'),
    ('Tom Petty', 'Rock'),
    ('Tom Waits', ' '),
    ('Train', 'Pop Rock'),
    ('Vampire Weekend', 'Indie Rock'),
    ('Van Morrison', 'Rock'),
    ('Violent Femmes', 'Alternative Rock'),
    ('Weezer', 'Alternative Rock'),
    ('Whitesnake', 'Hard Rock'),
    ('Wilco', 'Alternative Rock');