INSERT INTO Genre (genre_id, name)
VALUES ('1', 'Acid Jazz'),
    ('2', 'Afrobeat'),
    ('3', 'Alternative Country'),
    ('4', 'Alternative Rock'),
    ('5', 'Ambient'),
    ('6', 'Ambient Techno'),
    ('7', 'Art Rock'),
    ('8', 'Axé'),
    ('9', 'Bachata'),
    ('10', 'Banda'),
    ('11', 'Baroque'),
    ('12', 'Black Metal'),
    ('13', 'Bluegrass'),
    ('14', 'Blues'),
    ('15', 'Bossa Nova'),
    ('16', 'Breakbeat'),
    ('17', 'Britpop'),
    ('18', 'Celtic Music'),
    ('19', 'Chillwave'),
    ('20', 'Chiptune'),
    ('21', 'Classical'),
    ('22', 'Country'),
    ('23', 'Country Rock'),
    ('24', 'Cumbia'),
    ('25', 'Darkwave'),
    ('26', 'Death Metal'),
    ('27', 'Disco'),
    ('28', 'Doom Metal'),
    ('29', 'Downtempo'),
    ('30', 'Drone Music'),
    ('31', 'Drum And Bass'),
    ('32', 'Dub'),
    ('33', 'Dubstep'),
    ('34', 'Electro Swing'),
    ('35', 'Electronic'),
    ('36', 'Emo'),
    ('37', 'Eurodance'),
    ('38', 'Flamenco'),
    ('39', 'Folk'),
    ('40', 'Folk Metal'),
    ('41', 'Folk Rock'),
    ('42', 'Forró'),
    ('43', 'Funk'),
    ('44', 'Future Bass'),
    ('45', 'Future Garage'),
    ('46', 'Gamelan'),
    ('47', 'Garage Rock'),
    ('48', 'Glitch'),
    ('49', 'Glitch Hop'),
    ('50', 'Gospel'),
    ('51', 'Gothic Metal'),
    ('52', 'Gregorian Chant'),
    ('53', 'Grime'),
    ('54', 'Grunge'),
    ('55', 'Hard Rock'),
    ('56', 'Hard Trance'),
    ('57', 'Hardcore Punk'),
    ('58', 'Hardstyle'),
    ('59', 'Heavy Metal'),
    ('60', 'Hip Hop'),
    ('61', 'House'),
    ('62', 'Indie Folk'),
    ('63', 'Indie Pop'),
    ('64', 'Indie Rock'),
    ('65', 'Industrial'),
    ('66', 'J Pop'),
    ('67', 'Jazz'),
    ('68', 'K Pop'),
    ('69', 'Klezmer'),
    ('70', 'Latin'),
    ('71', 'Lo Fi'),
    ('72', 'Mariachi'),
    ('73', 'Medieval Music'),
    ('74', 'Merengue'),
    ('75', 'Metal'),
    ('76', 'Minimal Techno'),
    ('77', 'Neo Soul'),
    ('78', 'New Wave'),
    ('79', 'Noise Music'),
    ('80', 'Norteño'),
    ('81', 'Opera'),
    ('82', 'Pop'),
    ('83', 'Pop Rock'),
    ('84', 'Post Punk'),
    ('85', 'Post Rock'),
    ('86', 'Power Metal'),
    ('87', 'Prog Rock'),
    ('88', 'Proto Punk'),
    ('89', 'Psychedelic'),
    ('90', 'Psychedelic Rock'),
    ('91', 'Psytrance'),
    ('92', 'Punk'),
    ('93', 'Reggae'),
    ('94', 'Reggaeton'),
    ('95', 'Renaissance'),
    ('96', 'Rock'),
    ('97', 'Rock And Roll'),
    ('98', 'Salsa'),
    ('99', 'Samba'),
    ('100', 'Sertanejo'),
    ('101', 'Shibuya Kei'),
    ('102', 'Shoegaze'),
    ('103', 'Ska'),
    ('104', 'Ska Punk'),
    ('105', 'Soul'),
    ('106', 'Soundtrack'),
    ('107', 'Southern Rock'),
    ('108', 'Synthpop'),
    ('109', 'Techno'),
    ('110', 'Trance'),
    ('111', 'Trap'),
    ('112', 'Trip Hop'),
    ('113', 'Tropical House'),
    ('114', 'Uk Garage'),
    ('115', 'Vaporwave'),
    ('116', 'Visual Kei'),
    ('117', 'World Music'),
    ('118', 'Zouk');